Zotero scihub
zotero-chinese/wiki pull request #109
Opened 2023-12-14 12:27 UTC by Chikit-L

更新zotero-scihub插件介绍

2023-12-15 01:13 UTC, northword requested changes
此外，syt2 开发了兼容于 Zotero 7 的 SCIHub 插件，也可以加入文档：https://github.com/syt2/zotero-scipdf


---

新建分支时可以选择从 `upstream/main` 新建分支，以避免冲突。

直接在这个分支上继续提交就可以直接更改，如果不急的话也可以等周末我来改。

2023-12-15 01:13 UTC, northword commented on src/user-guide/plugins/Zotero-scihub.md
> +6.其中`"url":"https://sci-hub.se/{doi}"`, 可以进行为其他的Scihub镜像地址。
我对这种方法仅限于了解，我想知道这种方法会影响原生的抓取 PDF 全文的功能吗？

2023-12-15 01:13 UTC, northword commented on src/user-guide/plugins/Zotero-scihub.md
> +💡 Tips
`::: tip :::` 已经带了 `提示` 标题，不需要再手动加 Tip

2023-12-15 01:13 UTC, northword commented on src/user-guide/plugins/Zotero-scihub.md
> +- Scihub镜像地址：<https://sci-hub.se/、https://sci-hub.st/、https://sci-hub.ru/、https://www.sci-hub.ren/>
这里可以写成行内代码 
```suggestion
- zotero-scihub 的 GitHub 地址：<https://github.com/ethanwillis/zotero-scihub>
- 插件下载：[https://plugins.zotero-chinese.com/#/](https://plugins.zotero-chinese.com/#/)
- SciHub 镜像地址：`https://sci-hub.se/`、`https://sci-hub.st/`、`https://sci-hub.ru/`、`https://www.sci-hub.ren/`
```

2023-12-15 01:23 UTC, Chikit-L commented on src/user-guide/plugins/Zotero-scihub.md
> +6.其中`"url":"https://sci-hub.se/{doi}"`, 可以进行为其他的Scihub镜像地址。
说得对，这个好像是把原生的接口换掉了，写的时候忘记这个事情了。看了看官方对于这个功能的解释，应该是这个意思。https://www.zotero.org/support/kb/custom_pdf_resolvers

`新建分支时可以选择从 upstream/main 新建分支，以避免冲突。`
这个我再研究研究。

2023-12-15 01:31 UTC, northword commented on src/user-guide/plugins/Zotero-scihub.md
> +6.其中`"url":"https://sci-hub.se/{doi}"`, 可以进行为其他的Scihub镜像地址。
![image](https://github.com/zotero-chinese/wiki/assets/44738481/c7b43912-59dd-44a0-bc27-191ef30d316e)

![image](https://github.com/zotero-chinese/wiki/assets/44738481/75c4ab25-543f-491d-8619-7f022d4313be)

如果是这样的话，应该不会影响原生的，但我们不应直接替换这个值，而是把它们加入这个列表。（应该是吧）

2023-12-18 08:47 UTC, northword approved these changes

2023-12-18 08:47 UTC, merged