完善抓取文献条目信息的常见问题
zotero-chinese/wiki pull request #208
Opened 2024-06-19 16:00 UTC by wakewon

完善抓取文献条目信息的常见问题，加入重装 Zotero Connector的 说明，修改文档标题并调整在百科全书菜单中的位置。

2024-06-20 07:26 UTC, jiaojiaodubai commented
两个问题：
1. 点击跳转链接只会跳页面，不能定位到标题（虽然我们可能无法解决这个问题）
2. 示例图片的箭头和文字描述顺序不对应。

2024-06-20 07:32 UTC, wakewon commented
> 两个问题：
> 
> 1. 点击跳转链接只会跳页面，不能定位到标题（虽然我们可能无法解决这个问题）
> 2. 示例图片的箭头和文字描述顺序不对应。

1. 跳到标题这个我写链接的时候没有写到具体标题，不过也有一部分原因是希望完整阅读整个文档。
2. 图片有一些是多个步骤共用了一张图，我拆一下吧拆开会更清晰。

2024-06-20 07:42 UTC, jiaojiaodubai requested changes

2024-06-20 07:42 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
> +title: 抓取文献条目信息的常见问题
“的常见问题”不是必需的，因为它的父章节就叫“常见问题”

2024-06-20 07:42 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
> +- **橙色**的情况有正确的文献信息，可以正常引用，在手动补充附件后也可以在 Zotero 中阅读论文全文；
所谓“手动补充附件”应链接到“添加附件”一节？

2024-06-20 07:42 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
> +- **红色**的情况只有一个顶级附件，无法正常引用，必须为其创建/抓取一个条目后才能正常引用。
所谓“为其创建/抓取一个条目”应指向“添加条目”一节？

2024-06-20 07:42 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
> +Zotero 在网页上能抓取两类内容： **文献信息（文献条目的元数据）** ，以及相应的 **PDF 附件** 。
表述不严谨：
1. 是 Zotero Connector，不是 Zotero；
2. Connector 还能自动导入文献交换格式（.ris、.enw之类的）以及某些网站的 CSL style；
3. Connector 下载的附件不限于 PDF，还有图片、音频、视频、电子表格……之类的。

总之就是太片面了。

2024-06-20 07:42 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
> +- 一般来说，只要你在网页上或 Zotero 里 **能够正确地识别出文献类型** （条目图标是正常的文献类型图标，而不是“其他”或“网页”类型），就已经意味着你的文献信息/元数据 **抓取是成功的** 了。
有时，条目类型为“网页”是正常的，一个基本的判断方法是看条目类型和预期类型是否相符吧，比如想抓取的是一个期刊，那么抓取下来应该是期刊，如果这个网页不属于期刊、也不是会议论文……不属于任何一类特定的文献类型，我们只能笼统地把它抓取为“网页”

2024-06-20 07:42 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
> +   虽然 Zotero 目前已经支持在 Safari 中使用，但实际使用中在 Safari 中抓取失败的案例比较多。 \*\*建议使用 Microsoft Edge 或 Google Chrome 浏览器进行抓取。
其实最建议的是火狐，火狐上的 Connector 是 beta 的。

2024-06-20 07:48 UTC, wakewon commented on user-guide/faqs/update-translators.md
> +title: 抓取文献条目信息的常见问题
常见问题这一说法和插件、Word的文档保持了一致，我觉得不冲突。左边栏里没有写“的常见问题”，但作为页面的一级标题，完整表述文档的属性还是有必要的（毕竟直接走链接过来的人也不会看到左边栏里它的父章节。

2024-06-20 07:49 UTC, wakewon commented on user-guide/faqs/update-translators.md
> +- **橙色**的情况有正确的文献信息，可以正常引用，在手动补充附件后也可以在 Zotero 中阅读论文全文；
我加上吧，但感觉从这里跳转对应教程的需求应该不是太大

2024-06-20 07:53 UTC, wakewon commented on user-guide/faqs/update-translators.md
> +Zotero 在网页上能抓取两类内容： **文献信息（文献条目的元数据）** ，以及相应的 **PDF 附件** 。
1. 这里想表述的其实是 Zotero 这一整个解决方案（包括connector在内），不过俺格莱斯确实是Connector。
2和3我印象目前整个百科全书没有对这一部分做完整的说明，也和这篇文档面向的受众关系不太大。感觉这一点可以在添加条目那边做详细的澄清，这里只是对常见的情况做一点额外的提醒（过多的全面叙述反倒是可能会引发更多的疑问）

2024-06-20 07:55 UTC, wakewon commented on user-guide/faqs/update-translators.md
> +- 一般来说，只要你在网页上或 Zotero 里 **能够正确地识别出文献类型** （条目图标是正常的文献类型图标，而不是“其他”或“网页”类型），就已经意味着你的文献信息/元数据 **抓取是成功的** 了。
所以这里讲的是一般来说，这样的叙事还是针对这个文档的受众来写的。如果抓网页又得到了网页，感觉应该是不需要打开这篇文档的。或许需要找一个更直白同时也不失一般性的叙述方法

2024-06-20 07:56 UTC, wakewon commented on user-guide/faqs/update-translators.md
> +   虽然 Zotero 目前已经支持在 Safari 中使用，但实际使用中在 Safari 中抓取失败的案例比较多。 \*\*建议使用 Microsoft Edge 或 Google Chrome 浏览器进行抓取。
> 其实最建议的是火狐，火狐上的 Connector 是 beta 的。

目前来说我个人不建议火狐的原因是安装插件的时候需要额外注意另存为（减少客诉），在这次更新之前Chromium的抓取成功率也是足够的。

2024-06-20 07:59 UTC, wakewon commented on user-guide/faqs/update-translators.md
> +   虽然 Zotero 目前已经支持在 Safari 中使用，但实际使用中在 Safari 中抓取失败的案例比较多。 \*\*建议使用 Microsoft Edge 或 Google Chrome 浏览器进行抓取。
另一个原因是希望推荐一个主力浏览器，相对来说Firefox还是略小众了，也很难说只为了抓取文献特意选择Firefox。

2024-06-20 08:00 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
> +Zotero 在网页上能抓取两类内容： **文献信息（文献条目的元数据）** ，以及相应的 **PDF 附件** 。
那或许可以说“可以在抓取条目时连同PDF附件一同下载”，用“可以”这样的春秋笔法[doge]

2024-06-21 03:55 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
> +Zotero 文库中主要有三类内容： **文献条目，附件文件，笔记** 。其中，附件文件和笔记既可以附属于一篇文献的条目，也可以自己作为顶级项目独立存储在文库中。常见的条目类型以及常用的添加条目方法请阅读 [添加条目教程](../add-items.md) 。
“顶级”用“顶层”会不会好一点？，“项目”沿用“条目”就好吧，不然术语太多了。

“请阅读……”后面似乎多了一个空格。

2024-06-21 03:55 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
> +Zotero Connector 浏览器插件在网页上抓取文献时通常可以得到两类内容： **文献信息（文献条目的元数据）** ，以及相应的 **附件（如 PDF 全文、网页截图等）** 。
“浏览器插件” → “浏览器扩展”

2024-06-21 03:55 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
> +- 一般来说，只要你在网页上或 Zotero 里 **能够正确地识别出文献类型** （[条目图标](../add-items.md#条目-item)与该文献的类型相对应），就已经意味着你的文献信息/元数据 **抓取是成功的** 了。如果希望抓取的是`学位论文`，条目左边的图标却是`网页`或`期刊文章`，这通常意味着抓取失败或抓取到的部分信息不准确。
加粗的字两端似乎有冗余空格。

句式杂糅，“……已经成功了”和“……是成功的”，保留一种表述即可。

此外，对条目类型应用“`”标记有先例可循吗？它导致字体突变，如果仅表示强调，也许应该用其它标记。

2024-06-21 03:55 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
>  在使用 Zotero 的过程中，我们经常需要更新 translators 来实现从网页快速抓取文献信息。通常，我们可以借助 Zotero 本身的功能以及 茉莉花 插件快速完成该操作。但当 Zotero 或 茉莉花 插件出现故障无法完成一键自动更新时，我们也可以手动下载新版的 translators 文件，并进行手动更新。
话说，我们可以说“更新 translators”，这时候用复数是没有问题的，但“下载最新版的 translators 文件”这里用复数可能有问题，“translator 文件”应该是一个复合名词。

2024-06-21 03:55 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
> +   ![更新非官方维护中文翻译器](../../assets/images/image-update-unofficial-translators.jpg)
我认为这里的”非官方维护中文翻译器“也应该用引号括起来，因为”翻译器“是当时权宜的翻译，现在我们已经统一使用”转换器“作为其正式翻译，用引号括起来可以表示一种不那么正式的引述。

2024-06-21 03:55 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
> +   建议不定期来这里更新一下非官方维护中文 tranlator。特别是再遇到中文文献无法抓取的时候，通常意味着这里的 translator 需要更新了。
为什么前文用”翻译器/转换器“，这里又中英混杂了呢，也许应该统一一下？

”再遇到“→”在遇到“

2024-06-21 03:55 UTC, jiaojiaodubai commented on user-guide/plugins/better-notes.md
>  Zotero Better Notes 是由@windingwind 开发的，用于文献管理软件 Zotero 的笔记插件。它完全开源、免费，支持双链笔记，支持 Markdown 与标记语言，深度集成了文献管理与阅读功能。
”@“是一个西文字符，它前面也许应该有空格？

2024-06-21 03:55 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
>     [获取 Zotero Connector 下载链接](../install.md#浏览器插件-zotero-connector)
这个链接直接加在前面”升级 Zotero Connector 浏览器扩展“ 那里就好。

2024-06-21 04:08 UTC, northword commented on user-guide/faqs/update-translators.md
> +Zotero 文库中主要有三类内容： **文献条目，附件文件，笔记** 。其中，附件文件和笔记既可以附属于一篇文献的条目，也可以自己作为顶级项目独立存储在文库中。常见的条目类型以及常用的添加条目方法请阅读 [添加条目教程](../add-items.md) 。
我其实一直用的都是**顶级条目**，我个人也习惯在链接前后加空格。:)

2024-06-21 04:10 UTC, northword commented on user-guide/faqs/update-translators.md
> +- 一般来说，只要你在网页上或 Zotero 里 **能够正确地识别出文献类型** （[条目图标](../add-items.md#条目-item)与该文献的类型相对应），就已经意味着你的文献信息/元数据 **抓取是成功的** 了。如果希望抓取的是`学位论文`，条目左边的图标却是`网页`或`期刊文章`，这通常意味着抓取失败或抓取到的部分信息不准确。
在一句话中标记某个术语，我觉得用行间代码或引号都是可以接受的。或者你有什么其他方式推荐？

2024-06-21 04:16 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
> +- 一般来说，只要你在网页上或 Zotero 里 **能够正确地识别出文献类型** （[条目图标](../add-items.md#条目-item)与该文献的类型相对应），就已经意味着你的文献信息/元数据 **抓取是成功的** 了。如果希望抓取的是`学位论文`，条目左边的图标却是`网页`或`期刊文章`，这通常意味着抓取失败或抓取到的部分信息不准确。
对与眼前的 wiki 可以这么做，但在开发文档中应该避免滥用等宽标记，我遵守的规则是：仅对真正有可能写入到代码中的单词或短语使用等宽标记。

2024-06-21 04:46 UTC, wakewon commented on user-guide/faqs/update-translators.md
> +Zotero 文库中主要有三类内容： **文献条目，附件文件，笔记** 。其中，附件文件和笔记既可以附属于一篇文献的条目，也可以自己作为顶级项目独立存储在文库中。常见的条目类型以及常用的添加条目方法请阅读 [添加条目教程](../add-items.md) 。
顶级和顶层可以看下统一下说法，这个我感觉都可以。

项目和条目的属于我应该是刻意区分开的。我觉得从我自己的理解上，想把条目定成具有条目信息和“文献”类型的那一条信息，而无论是附件还是笔记，都是一个实体项目而非条目信息。进一步讲，我希望达到的效果是有条目=能引用，没有条目=不能引用。特别是只有一个 PDF 附件作为顶级项目的时候不希望被称为是有条目的状态。

链接和一些名词是有专门加一个空格来做区分和强调（文中涉及到插件名的时候，有时候也专门前后加了个空格拆开）。**我觉得核心需求是这一类专有名词需要有一种样式规范来强调一下**，与正文区分开。目前我用的是前后加空格和代码块，加粗的视觉效果区分度不高。

2024-06-21 04:48 UTC, wakewon commented on user-guide/faqs/update-translators.md
> +Zotero Connector 浏览器插件在网页上抓取文献时通常可以得到两类内容： **文献信息（文献条目的元数据）** ，以及相应的 **附件（如 PDF 全文、网页截图等）** 。
Good idea，这样可以跟 Zotero 插件区分开一点。

2024-06-21 04:57 UTC, wakewon commented on user-guide/faqs/update-translators.md
> +- 一般来说，只要你在网页上或 Zotero 里 **能够正确地识别出文献类型** （[条目图标](../add-items.md#条目-item)与该文献的类型相对应），就已经意味着你的文献信息/元数据 **抓取是成功的** 了。如果希望抓取的是`学位论文`，条目左边的图标却是`网页`或`期刊文章`，这通常意味着抓取失败或抓取到的部分信息不准确。
> 对与眼前的 wiki 可以这么做，但在开发文档中应该避免滥用等宽标记，我遵守的规则是：仅对真正有可能写入到代码中的单词或短语使用等宽标记。

1. 冗余空格是专门加入的，根源上应该是最初在Gitee Issue里加粗的时候会自动加上空格，后面文档也就沿用了这个方式来做强调。

2. 删漏了2333

3. 其实还是缺乏一种将术语高亮的标记样式了，选用等宽仅仅是因为它是原生md语法里视觉效果最好的术语强调方法（两端加空格也是出于同种无奈）。

2024-06-21 05:01 UTC, wakewon commented on user-guide/faqs/update-translators.md
>  在使用 Zotero 的过程中，我们经常需要更新 translators 来实现从网页快速抓取文献信息。通常，我们可以借助 Zotero 本身的功能以及 茉莉花 插件快速完成该操作。但当 Zotero 或 茉莉花 插件出现故障无法完成一键自动更新时，我们也可以手动下载新版的 translators 文件，并进行手动更新。
中英混杂是有这个问题，但现在 Zotero 做不到完全的汉化（汉语翻译也不统一），早期文档就这样暴力处理让它看起来和界面/路径一致。或许这里完全采用转换器的说法，然后时不时用“转换器（translators）”来提醒一下大家这两个的关系会更严谨？

2024-06-21 05:03 UTC, wakewon commented on user-guide/faqs/update-translators.md
> +   ![更新非官方维护中文翻译器](../../assets/images/image-update-unofficial-translators.jpg)
这里建议茉莉花在后续更新的时候更新下这里的用词，文档里这么写完全是为了正确指引界面上的位置。图注目前是无所谓的，现在线上文档似乎默认不显示图注内容。

2024-06-21 05:07 UTC, wakewon commented on user-guide/faqs/update-translators.md
> +   建议不定期来这里更新一下非官方维护中文 tranlator。特别是再遇到中文文献无法抓取的时候，通常意味着这里的 translator 需要更新了。
官方目前用的很杂糅，也让文档在指引的时候非常困扰，特别是有很多人并不会一行一行看一些细节的解释。这一版文档我先统一成转换器吧，看看后续反馈如何。

“再遇到”其实不是一个typo，不过“在遇到”也行。

2024-06-21 05:07 UTC, wakewon commented on user-guide/plugins/better-notes.md
>  Zotero Better Notes 是由@windingwind 开发的，用于文献管理软件 Zotero 的笔记插件。它完全开源、免费，支持双链笔记，支持 Markdown 与标记语言，深度集成了文献管理与阅读功能。
fixed

2024-06-21 05:24 UTC, wakewon commented on user-guide/faqs/update-translators.md
> +   ![更新非官方维护中文翻译器](../../assets/images/image-update-unofficial-translators.jpg)
> 这里建议茉莉花在后续更新的时候更新下这里的用词，文档里这么写完全是为了正确指引界面上的位置。图注目前是无所谓的，现在线上文档似乎默认不显示图注内容。

刚看了下茉莉花在 Zotero 7 上已经是说的转换器了，Zotero 6 上我没有看。

2024-06-21 05:35 UTC, wakewon commented on user-guide/faqs/update-translators.md
>     [获取 Zotero Connector 下载链接](../install.md#浏览器插件-zotero-connector)
fixed

2024-06-21 07:48 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
> +   ![更新非官方维护中文翻译器](../../assets/images/image-update-unofficial-translators.jpg)
Zotero 6上面是“翻译器”（历史遗留）

2024-06-21 07:49 UTC, jiaojiaodubai commented on user-guide/faqs/update-translators.md
> +Zotero 文库中主要有三类内容： **文献条目，附件文件，笔记** 。其中，附件文件和笔记既可以附属于一篇文献的条目，也可以自己作为顶级项目独立存储在文库中。常见的条目类型以及常用的添加条目方法请阅读 [添加条目教程](../add-items.md) 。
@northword 如果链接前后有空格是文档的风格规范的话，就写到文档风格那章里面吧。

2024-06-21 07:50 UTC, jiaojiaodubai approved these changes

2024-06-21 07:51 UTC, jiaojiaodubai commented
链接前后有无空格的风格尚未统一（这一点可以在预览中清楚地看到）

2024-06-21 08:06 UTC, northword approved these changes
请稍后合并等我压缩一下图片

2024-06-21 09:09 UTC, merged