添加 ZotMoov 插件的介绍页面
zotero-chinese/wiki pull request #307
Opened 2024-11-25 15:18 UTC by Morimiue

ZotMoov 插件用于管理 PDF 等文献附件，是 Zotero 6 时代的 ZotFile 的替代品，我相信会有很多人需要它，特别是需要云同步的朋友。

2024-11-25 15:36 UTC, Morimiue commented
这个 CI 流程是不是不太对啊，为啥如果“运行 Lint 检查”出错，反而不执行“运行 Lint 修复”了（

2024-11-25 15:43 UTC, northword commented
> 这个 CI 流程是不是不太对啊，为啥如果“运行 Lint 检查”出错，反而不执行“运行 Lint 修复”了（

这一块由于 pr 触发的 ci 存在权限问题，暂时没有解决由 ci 提交到 pr 分支相关的操作。

Lint 这个您可以暂时先不管，它似乎是由于仓库中已有的其他文件导致的错误。

如果其他几位成员对内容没有意见，我们将在明天处理这个 PR。

感谢您的贡献！

2024-11-25 15:58 UTC, northword requested changes
感谢贡献！

我们讨论后，认为有必要在「配合同步」这一块添加一个「警告」。

2024-11-25 15:58 UTC, northword commented on user-guide/plugins/zotmoov.md
> +### 搭配云同步
我们有必要在这里强调/澄清：

- 当拟使用的同步服务支持 WebDAV 时，优先使用 WebDAV；推荐仅当拟使用的同步服务不支持 WebDAV 时，再使用这种方式。
- 这种方式不支持同步到 Zotero 官方 iOS 和 Android 客户端。

我们尊重通过各种途径进行同步的方式，只是确实收到了太多的关于 ZotFile 相关的问题和反馈（大多数都是错误理解了 ZotFile 在同步中的作用，并且多数都是本不需要 ZotFile 的），所以为了让非极客用户能明白自己是否真的需要这个插件，推荐在这里添加一个警告块。

2024-11-26 01:17 UTC, Morimiue commented on user-guide/plugins/zotmoov.md
> +### 搭配云同步
我觉得你们说的很有道理，我将在此添加一个警告。

2024-11-26 04:23 UTC, northword approved these changes

2024-11-26 04:26 UTC, merged

2024-11-26 04:26 UTC, northword commented
Thanks!