Update wps-plugin.md
zotero-chinese/wiki pull request #333
Opened 2024-12-28 08:47 UTC by bigben446

2024-12-28 09:48 UTC, northword requested changes
感谢贡献！

@l0o0 关于 WPS 的这篇文档先前是由你编写的，你有兴趣看一下这个如何修改吗？

2024-12-28 09:48 UTC, northword commented on user-guide/wps-plugin.md
> +
gitee:wangrui5015/Zotero-WPSJS 与 WPS JavaScript API 插件方法其实是一个方法，现有的文档可能需要根据修改版插件进行修改。

- Windows 用户不需要手动安装 Python，之需要手动执行 exe 文件了（而不是 bat），
- 而 Linux 是运行 sh 脚本
- macOS 用户可以使用了
- macOS 和 Linux 需要链接“更新 Python”方面的内容
- 需要添加“信任宏”相关的描述

2024-12-31 11:56 UTC, l0o0 commented
> 感谢贡献！
> 
> @l0o0 关于 WPS 的这篇文档先前是由你编写的，你有兴趣看一下这个如何修改吗？

收到。

2025-05-23 08:25 UTC, northword approved these changes

2025-05-23 08:25 UTC, merged