blog-isharestuff-V0.0.1
zotero-chinese/wiki pull request #8
Opened 2023-09-15 06:24 UTC by iShareStuff

2023-09-15 06:29 UTC, iShareStuff commented
ok

2023-09-15 06:36 UTC, northword requested changes

2023-09-15 06:36 UTC, northword commented on _resources/6633a5f8c3b54ca386551486e98caed7.png
所有的图形资源都应放入`src/assets`

2023-09-15 06:36 UTC, northword commented on src/.vuepress/bulletin.js
这是在什么地方用的？

2023-09-15 06:36 UTC, northword commented on src/.vuepress/navbar.ts
> + */
我觉得头部版权注释是不必要的

2023-09-15 06:36 UTC, northword commented on src/.vuepress/navbar.ts
> +  },
vuepress-theme-hope 提供了公告板，不需要写在nav里

2023-09-15 06:36 UTC, northword commented on src/user-guide/Zotero Better Notes/0 文档简介_About.md
成组的插件文档可以单开仓库，或是放入“插件与功能扩展”里面

2023-09-15 06:36 UTC, northword commented on src/user-guide/生成引注_参考文献表/在 Word 中插入引文.md
不要覆盖已有的文档，已有的文档基本已经完成了校对。

2023-09-15 06:36 UTC, northword commented on src/user-guide/生成引注_参考文献表/在 Word 中插入引文.md
> +<img src="https://cdn.nlark.com/yuque/0/2022/png/2804696/1662207437935-9f328140-4863-4ec1-b528-51073ef2c8f3.png" width="603" id="ubd2bb440" class="ne-image">
这里的 cdn 是哪里提供的？可靠不？

我个人倾向于图片在仓库保存，仓库有机器人会定期压缩图片。

2023-09-15 06:38 UTC, northword commented on _resources/6633a5f8c3b54ca386551486e98caed7.png
此外那个接近6M的图我觉得可以不放，或者找其他地方方成可编辑的在线文档。这个图打开几次就把 Netlify 的流量耗完了，我们目前每个月只有 100G 的流量。

2023-09-15 06:40 UTC, iShareStuff commented
> 这是在什么地方用的？ 

删掉了 不需要

2023-09-15 06:43 UTC, iShareStuff commented
> vuepress-theme-hope 提供了公告板，不需要写在nav里 

写在哪里  我用的模板不是hope 对这个不是很熟悉 是主页吗？

2023-09-15 06:44 UTC, northword requested changes
此外，目前网站依靠文件编号来实现侧边栏排序，如果这一方式不妥，我看可以改成在.vuepress/sidebar.ts里手动排序。
依靠编号自动排序需要对每一个目录都有 `README.md` 用来指定目录显示在侧边栏的名称。

2023-09-15 06:44 UTC, northword commented on src/public/README.md
我建议 vip 网站单开仓库，不要签入 wiki 仓库，wiki 仓库目标是吸引所有人都编辑，最好不放任何和付费有关的东西。单开仓库，可以在首页或 nav 加链接过去。

2023-09-15 06:44 UTC, northword commented on src/plugin-dev-guide/0 基础知识.md
开发文档其实已经严重过时了，很多东西都已经不再适用于 Zotero 7 了，所以我在写把它迁移过来的必要性。

2023-09-15 06:44 UTC, northword commented on .vscode/settings.json
> +"LICENSE": true
这里的缩进是不是被改了

2023-09-15 06:52 UTC, northword commented
> > vuepress-theme-hope 提供了公告板，不需要写在nav里
> 
> 写在哪里 我用的模板不是hope 对这个不是很熟悉 是主页吗？

https://github.com/zotero-chinese/wiki/pull/8#discussion_r1326865205 ，如我在这里所说，我不建议把 vip 有关的内容签入这个仓库，我建议单独开一个仓库，首页链接过去。

这个仓库不只是组织里的人，也会吸引一些志愿者编辑，如前几天就有一位同学贡献了好几篇，我觉得带上付费的相关文档会影响他人的积极性。

至于公告板，是我记错了，这是 vuepress 插件提供的：https://marketplace.vuejs.press/zh/plugins/feature.html

2023-09-15 07:04 UTC, northword requested changes

2023-09-15 07:04 UTC, northword commented on src/.vuepress/navbar.ts
>    { text: "首页", icon: "home", link: "/" },
这一行与第12行是重复的，需要移除第12行，保留“首页”；否则会出现两个首页
![图片](https://github.com/zotero-chinese/wiki/assets/44738481/9b2cb052-8719-403a-ba58-ceedfb9d1b00)

2024-02-02 06:45 UTC, northword commented
已被 #126，#125，#120，#106，#64，#63 分批实现。

2024-02-02 06:45 UTC, closed without merging